tools:
  - class_name: "recipe.async_dapo_tool.custom_unit_multi_turn.CustomSandboxFusionTool"
    config:
      sandbox_fusion_url: "http://10.127.16.170:28893/run"
      num_workers: 256
      enable_global_rate_limit: true
      rate_limit: 256
      default_timeout: 30
      default_language: "python"
      memory_limit_mb: 4096
      type: native

    tool_schema:
      type: "function"
      function:
        name: "code_interpreter"
        description: "A tool for executing code."
        parameters:
          type: "object"
          properties:
            code:
              type: "string"
              description: "The code to execute."
          required: ["code"]
