apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: hgl-verl-vllm082
spec:
  minAvailable: 2
  schedulerName: volcano
  queue: chatrl
  plugins:
    pytorch: ["--port=25431"]
    svc: ["--disable-network-policy=true"]
  tasks:
    - replicas: 1
      name: master
      template:
        spec:
          restartPolicy: Never
          hostNetwork: true
          dnsPolicy: ClusterFirstWithHostNet
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: kubernetes.io/hostname 
                        operator: In
                        values:
                          - zjzx1h-402-c-16-a1p1-sev-h100-08u05
          initContainers: #不修改，本次升级改动
            - name: init
              image: harbor.telecom-ai.com.cn/teleinfra/alpine:latest
              command: ["/bin/ash"]
              args: 
                - "-c"
                - cp /nvfile-heatstorage/teleai-infra/look_mlxdevice.sh /ib-config
              volumeMounts:
                - name: shared-volume
                  mountPath: /nvfile-heatstorage
                - name: ib-config
                  mountPath: /ib-config
          containers:
            - name: worker
              resources:
                requests:
                  cpu: 64
                  memory: 512G
                  nvidia.com/gpu: 8
                limits:
                  cpu: 64
                  memory: 512G
                  nvidia.com/gpu: 8
              image: harbor.telecom-ai.com.cn/chatrl/verl:ngc-th2.6.0-cu120-vllm0.8.2
              command: ["/bin/bash"]
              args:
                - "-c"
                - |
                  export NCCL_IB_HCA=$(/ib-config/look_mlxdevice.sh) #必须有，不修改，本次升级改动
                  echo NCCL_IB_HCA=$NCCL_IB_HCA

                  rm -f /etc/pip.conf /etc/xdg/pip/pip.conf /root/.pip/pip.conf /root/.config/pip/pip.conf /usr/pip.conf \
                  && pip3 config set global.index-url http://pypi.chinatelecom.ai/simple \
                  && pip3 config set install.trusted-host pypi.chinatelecom.ai

                  # cp model from shared storage
                  mkdir models/
                  cp -r /nvfile-heatstorage/chatrl/public/models/Qwen25-7B-Base-change-chat-template models/
                  cp -r /nvfile-heatstorage/chatrl/public/models/DeepSeek-R1-Distill-Llama-8B models/

                  mkdir datasets/
                  mkdir -p datasets/dapo
                  cp -r /nvfile-heatstorage/chatrl/users/hxh/data/rule_based_rl/DAPO-Math-17k/data/dapo-math-17k.parquet datasets/dapo/
                  cp -r /nvfile-heatstorage/chatrl/users/hxh/data/rule_based_rl/DAPO-AIME-2024/data/aime-2024.parquet datasets/dapo/


                  # install verl
                  cp -r /nvfile-heatstorage/chatrl/users/heguoliang/hgl-verl .
                  pip install -v -e .
                  echo $MASTER_PORT

                  # 
                  pip install megatron-core==0.11.0

                  # 
                  ray start --head  --port=$MASTER_PORT --block

                  # sleep 10
                  # ./examples/grpo_trainer/run_qwen2-7b-2node-realbs256-lr4e-7_maxlen16k-vllm_0_8_2.sh 2>&1 | tee logs/run_qwen2-7b-2node-realbs256-lr4e-7_maxlen16k-vllm_0_8_2.log
              securityContext:
                privileged: true
                # capabilities:
                #   add: [ "IPC_LOCK" ]
              # ports:
              #   - containerPort: 5670
              # workingDir: /nvfile-heatstorage/teleai-infra/adk/t2v
              volumeMounts:
                - name: dshm
                  mountPath: /dev/shm
                - name: shared-volume
                  mountPath: /nvfile-heatstorage
                - name: ib-config #必须有，不修改，本次升级改动
                  mountPath: /ib-config
                - name: data02
                  mountPath: /data02
                - name: vscode
                  mountPath: /root
                - name: vsixs
                  mountPath: /workspace/vsixs
          volumes:
            - name: dshm
              emptyDir:
                medium: Memory
              # hostPath:
              #   path: /dev/shm
              #   type: Directory
            - name: shared-volume
              hostPath:
                path: /nvfile-heatstorage
                type: Directory
            - name: ib-config #必须有，不修改，本次升级改动
              emptyDir:
                medium: ""
                sizeLimit: "500Mi"
            - name: vscode
              hostPath:
                path: /nvfile-heatstorage/tele_data_share/public
                type: Directory
            - name: data02
              hostPath:
                path: /data02
                type: Directory
            - name: vsixs
              hostPath:
                path: /nvfile-heatstorage/tele_data_share/public/vsixs
          securityContext:
            runAsUser: 0
    - replicas: 1
      name: worker
      template:
        spec:
          restartPolicy: Never
          hostNetwork: true
          dnsPolicy: ClusterFirstWithHostNet
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: team
                        operator: In
                        values:
                          -  rlib-debug
                      # - key: kubernetes.io/hostname 
                      #   operator: In
                      #   values:
                      #     - zjzx1h-402-b-15-a1p1-sev-h100-08u05
                          # - zjzx1h-402-b-15-a1p1-sev-h100-08u05
          initContainers: #不修改，本次升级改动
            - name: init
              image: harbor.telecom-ai.com.cn/teleinfra/alpine:latest
              command: ["/bin/ash"]
              args: 
                - "-c"
                - cp /nvfile-heatstorage/teleai-infra/look_mlxdevice.sh /ib-config
              volumeMounts:
                - name: shared-volume
                  mountPath: /nvfile-heatstorage
                - name: ib-config
                  mountPath: /ib-config
          containers:
            - name: worker
              resources:
                requests:
                  cpu: 64
                  memory: 512G
                  nvidia.com/gpu: 8
                limits:
                  cpu: 64
                  memory: 512G
                  nvidia.com/gpu: 8
              image: harbor.telecom-ai.com.cn/chatrl/verl:ngc-th2.6.0-cu120-vllm0.8.2
              command: ["/bin/bash"]
              args:
                - "-c"
                - |
                  export NCCL_IB_HCA=$(/ib-config/look_mlxdevice.sh) #必须有，不修改，本次升级改动
                  echo NCCL_IB_HCA=$NCCL_IB_HCA

                  rm -f /etc/pip.conf /etc/xdg/pip/pip.conf /root/.pip/pip.conf /root/.config/pip/pip.conf /usr/pip.conf \
                  && pip3 config set global.index-url http://pypi.chinatelecom.ai/simple \
                  && pip3 config set install.trusted-host pypi.chinatelecom.ai

                  # cp model from shared storage
                  mkdir models/
                  cp -r /nvfile-heatstorage/chatrl/public/models/Qwen25-7B-Base-change-chat-template models/
                  cp -r /nvfile-heatstorage/chatrl/public/models/DeepSeek-R1-Distill-Llama-8B models/

                  mkdir datasets/
                  mkdir -p datasets/dapo
                  cp -r /nvfile-heatstorage/chatrl/users/hxh/data/rule_based_rl/DAPO-Math-17k/data/dapo-math-17k.parquet datasets/dapo/
                  cp -r /nvfile-heatstorage/chatrl/users/hxh/data/rule_based_rl/DAPO-AIME-2024/data/aime-2024.parquet datasets/dapo/


                  # install verl
                  cp -r /nvfile-heatstorage/chatrl/users/heguoliang/hgl-verl .
                  pip install -v -e .
                  echo $MASTER_PORT

                  # 
                  pip install megatron-core==0.11.0

                  # 
                  ray start --head  --port=$MASTER_PORT --block

                  # sleep 10
                  # ./examples/grpo_trainer/run_qwen2-7b-2node-realbs256-lr4e-7_maxlen16k-vllm_0_8_2.sh 2>&1 | tee logs/run_qwen2-7b-2node-realbs256-lr4e-7_maxlen16k-vllm_0_8_2.log
              securityContext:
                privileged: true
                # capabilities:
                #   add: [ "IPC_LOCK" ]
              # ports:
              #   - containerPort: 5670
              # workingDir: /nvfile-heatstorage/teleai-infra/adk/t2v
              volumeMounts:
                - name: dshm
                  mountPath: /dev/shm
                - name: shared-volume
                  mountPath: /nvfile-heatstorage
                - name: ib-config #必须有，不修改，本次升级改动
                  mountPath: /ib-config
                - name: data02
                  mountPath: /data02
                - name: vscode
                  mountPath: /root
                - name: vsixs
                  mountPath: /workspace/vsixs
          volumes:
            - name: dshm
              emptyDir:
                medium: Memory
              # hostPath:
              #   path: /dev/shm
              #   type: Directory
            - name: shared-volume
              hostPath:
                path: /nvfile-heatstorage
                type: Directory
            - name: ib-config #必须有，不修改，本次升级改动
              emptyDir:
                medium: ""
                sizeLimit: "500Mi"
            - name: vscode
              hostPath:
                path: /nvfile-heatstorage/tele_data_share/public
                type: Directory
            - name: data02
              hostPath:
                path: /data02
                type: Directory
            - name: vsixs
              hostPath:
                path: /nvfile-heatstorage/tele_data_share/public/vsixs
          securityContext:
            runAsUser: 0