# Copyright 2024 Bytedance Ltd. and/or its affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import asyncio
import json
import logging
import os
import re
from urllib.parse import urlparse

import aiohttp
from openai.types.chat import ChatCompletion

from verl import DataProto
from verl.single_controller.ray.base import RayWorkerGroup
from verl.workers.config import RewardModelConfig
from verl.experimental.reward.api.base import OpenAIClientTool

logger = logging.getLogger(__file__)
logger.setLevel(os.getenv("VERL_LOGGING_LEVEL", "WARN"))

# LLM-as-a-Judge 配置常量
BASE_URL = os.getenv("REWARD_MODEL_BASE_URL", os.getenv("base_url", "http://app-2abf503c001748c4967f6b495c322ffc.ns-bjdianxin-cb517126.svc.cluster.local:6669/v1"))
API_KEY = os.getenv("REWARD_MODEL_API_KEY", os.getenv("api_key", "EMPTY"))
MODEL_NAME = os.getenv("REWARD_MODEL_NAME", os.getenv("judge_model_name", "Qwen3-30B-A3B"))
MAX_WORKERS = int(os.getenv("REWARD_MODEL_MAX_WORKERS", os.getenv("JUDGE_MAX_WORKERS", "32")))
# 超时和重试配置
OPENAI_TIMEOUT = float(os.getenv("OPENAI_TIMEOUT", "30.0"))  # 默认600秒
OPENAI_MAX_RETRIES = int(os.getenv("OPENAI_MAX_RETRIES", "3"))  # 默认3次重试

# 提示模板
IMPROVED_PROMPT_TEMPLATE = '''I will now give you a question, an answer generated by an AI assistant, and the correct answer to the question. Please compare the AI assistant's answer with the correct answer and determine whether they are consistent.

Important: You do not need to compute or solve the problem yourself. Just judge whether the AI Assistant Answer matches the provided Ground Truth; use the question text only as context if needed.

- ---------------- [Question Start] -----------------

{problem}

- ---------------- [Question End] -----------------
- ---------------- [AI Assistant Answer Start] -----------------

{pred}

- ---------------- [AI Assistant Answer End] -----------------
- ---------------- [Ground Truth Start] -----------------

{ground_truth}

- ---------------- [Ground Truth End] -----------------

Please structure your response in three lines:
1. Line 1: Analyze the AI assistant's answer
2. Line 2: Confirm what the correct answer is
3. Line 3: Analyze the question to judge whether the AI assistant's answer is consistent with the correct answer. Provide your conclusion, consistent or inconsistent, in English within <result></result> tags, i.e., <result>consistent</result> or <result>inconsistent</result>

Do not output anything other than the above.

Output:
'''.strip()


def _normalize_text(value, max_join: int = 16384):
    """将任意输入规范化为字符串，尽可能提取可阅读的文本内容。"""
    try:
        if value is None:
            return ""
        if isinstance(value, str):
            return value
        if isinstance(value, bytes):
            try:
                return value.decode("utf-8", errors="ignore")
            except Exception:
                return ""
        if isinstance(value, list):
            if len(value) == 0:
                return ""
            if all(isinstance(it, dict) for it in value) and any("content" in it for it in value):
                parts = [str(it.get("content", "")) for it in value]
                joined = "\n".join(parts)
                return joined[:max_join]
            return _normalize_text(value[0], max_join=max_join)
        if isinstance(value, dict):
            if "messages" in value and isinstance(value["messages"], list):
                return _normalize_text(value["messages"], max_join=max_join)
            for key in ("content", "text", "question", "prompt", "answer"):
                if key in value and value[key] is not None:
                    return _normalize_text(value[key], max_join=max_join)
            try:
                return json.dumps(value, ensure_ascii=False, separators=(",", ":"))[:max_join]
            except Exception:
                return str(value)[:max_join]
        return str(value)[:max_join]
    except Exception:
        return ""


def match_answer_content(processed_str, answer_pattern=r"(?i)Answer\s*:\s*([^\n]+)"):
    """从响应文本中提取答案内容。"""
    matches = list(re.finditer(answer_pattern, processed_str, re.DOTALL))
    if not matches:
        return None
    final_answer = matches[-1].group(1).strip()
    return final_answer


def compute_reward_result_tag(judge_response):
    """从 judge 模型响应中提取判定结果标签。
    
    返回与规则计算一致的奖励值：
    - 1.0: 答案正确（consistent）
    - -1.0: 答案错误（inconsistent）或解析失败
    
    Args:
        judge_response: judge模型的响应文本
        
    Returns:
        float: 奖励分数，1.0表示正确，-1.0表示错误
    """
    if not judge_response:
        return -1.0
    
    result_match = re.findall(r"<result>(.*?)</result>", judge_response)
    if result_match and len(result_match) >= 1:
        try:
            judge_item_res = result_match[-1].strip().lower() == "consistent"
            # 返回浮点数，与规则计算一致：1.0表示正确，-1.0表示错误
            return 1.0 if judge_item_res else -1.0
        except Exception as e:
            logger.warning(f"Match error in judge response: {e}")
            return -1.0
    else:
        # 如果没有找到result标签，认为judge失败，返回-1.0（错误）
        logger.warning(f"No result tag found in judge response: {judge_response[:200]}")
        return -1.0


class RewardModelManager:
    """Reward model manager using LLM-as-a-Judge via remote API."""

    def __init__(self, config: RewardModelConfig, worker_group: RayWorkerGroup = None):
        """
        Initialize the reward model manager.

        Args:
            config (RewardModelConfig): Reward model configuration.
            worker_group (RayWorkerGroup, optional): Worker group. Defaults to None.
        """
        self.config = config
        self.worker_group = worker_group
        self._initialize_llm_judge_client()

    def _initialize_llm_judge_client(self):
        """初始化 LLM-as-a-Judge 客户端。"""
        self.client = OpenAIClientTool(
            name=MODEL_NAME,
            api_key=API_KEY,
            base_url=BASE_URL,
            timeout=OPENAI_TIMEOUT,
            max_retries=OPENAI_MAX_RETRIES
        )
        # 为了保持接口兼容性，补充这些属性
        self.tokenizer = None  # 使用远程 API，不需要 tokenizer
        self.rollout_replicas = []  # 使用远程 API，不需要本地 replicas
        self.server_handles = []
        self.server_addresses = []
        self.router_address = None  # 使用远程 API，无需本地 router
        logger.info(f"RewardModelManager initialized with remote API: {BASE_URL}, model: {MODEL_NAME}, timeout: {OPENAI_TIMEOUT}s, max_retries: {OPENAI_MAX_RETRIES}")

    def get_router_address(self):
        """Return a router-like address (host:port) parsed from BASE_URL for compatibility."""
        try:
            parsed = urlparse(BASE_URL)
            # Expected BASE_URL like: http://127.0.0.1:6665/v1
            return parsed.netloc or None
        except Exception:
            return None

    def wake_up(self):
        """空实现，远程 API 无需唤醒。"""
        pass

    def sleep(self):
        """空实现，远程 API 无需休眠。"""
        pass

    async def chat_complete(self, chat_complete_request: dict):
        """调用远程 API 的 chat completion。"""
        messages = chat_complete_request["messages"]
        gen_args = {
            "model_name": MODEL_NAME,
            "temperature": chat_complete_request.get("temperature", 0.7),
            "top_p": chat_complete_request.get("top_p", 1.0),
            "max_tokens": chat_complete_request.get("max_tokens", 2048),
            "workers": MAX_WORKERS
        }
        
        try:
            judge_output = self.client.generate(messages, **gen_args)
            response = judge_output[0] if judge_output else None
            # 转换为 ChatCompletion 以保持接口一致
            from openai.types.chat import ChatCompletion, ChatCompletionMessage
            return ChatCompletion(
                id="dummy-id",
                choices=[{
                    "finish_reason": "stop",
                    "index": 0,
                    "message": ChatCompletionMessage(
                        role="assistant",
                        content=response or ""
                    )
                }],
                created=0,
                model=MODEL_NAME,
                object="chat.completion"
            )
        except Exception as e:
            logger.error(f"Remote API chat_complete failed: {e}")
            raise

    def _run_all(self, tasks: list[asyncio.Task]):
        async def run_all():
            return await asyncio.gather(*tasks)

        return asyncio.run(run_all())

    def generate_sequences(self, prompts: DataProto, sampling_params: dict):
        """生成序列，保持与原始接口一致。"""
        chat_complete_requests = [
            {
                "messages": list(messages),
                **sampling_params,
            }
            for messages in prompts.non_tensor_batch.get("raw_prompt")
        ]
        tasks = [self.chat_complete(chat_complete_request) for chat_complete_request in chat_complete_requests]
        results = self._run_all(tasks)
        return results
