# Copyright 2025 Bytedance Ltd. and/or its affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
import json
from concurrent.futures import ThreadPoolExecutor
from time import sleep

import requests
import re
from verl.utils.reward_score.math import last_boxed_only_string, remove_boxed
from .api.base import OpenAIClientTool


# BASE_URL = "http://127.0.0.1:6664/v1" # qwen25 32b instruct
BASE_URL = "http://111.31.225.52:6665/v1" # qwen3 30b a3b
API_KEY = "EMPTY"
MAX_RETRIES = 3
BASE_DELAY = 2

MAX_WORKERS = 50
MAX_WORKERS = 50
# MODEL_NAME = "Qwen2.5-32B-Instruct"
MODEL_NAME = "Qwen3-30B-A3B"
SAVE_JUDGE_PATH = "/afs/chatrl/users/hwq/code/verl-remote-reward/examples_sensecore/grpo_remote_reward/output.jsonl"  # 设置你要保存的 JSONL 文件路径


# 供训练阶段动态覆写
def init_remote_reward(cfg: dict | None = None):
    """Inject cfg from Hydra once at program start."""
    global BASE_URL, API_KEY, MODEL_NAME, SAVE_JUDGE_PATH
    if not cfg:
        return
    BASE_URL   = cfg.get("base_url",  BASE_URL)
    API_KEY    = cfg.get("api_key",   API_KEY)
    MODEL_NAME = cfg.get("model_name",MODEL_NAME)
    SAVE_JUDGE_PATH = cfg.get("save_judge_path",SAVE_JUDGE_PATH)
    print("----------------------------SAVE_JUDGE_PATH-----------------------------------")
    print(SAVE_JUDGE_PATH)

PROMPT_TEMPLATE_FROM_RESPONSE = '''I will now give you a question, an answer generated by an AI assistant, and the correct answer to the question. Please first extract the final answer stated by the AI assistant from its response, then compare it with the correct answer to decide whether they are consistent.

Important: You do not need to compute or solve the problem yourself. Use the question text only as context if needed; base your decision on the AI assistant’s extracted final answer and the provided correct answer.

----------------- [Question Start] -----------------

{problem}

----------------- [Question End] -----------------


----------------- [AI Assistant Answer Start] -----------------

{pred}

----------------- [AI Assistant Answer End] -----------------


----------------- [Correct Answer Start] -----------------

{ground_truth}

----------------- [Correct Answer End] -----------------

Please structure your response in three lines:
1. Line 1: Analyze the AI assistant’s response and EXTRACT the final answer it gives, as a specific value (numeric if applicable). Notes:
   1.1 Some responses truncate earlier steps and only keep the trailing key part—just extract the final answer from what remains.
   1.2 If the solution steps disagree with the final “Answer:”/“Final answer:” tag, take the value after that tag as the model’s final answer.
2. Line 2: Confirm what the correct (ground-truth) answer is.
3. Line 3: Judge whether the AI assistant’s final answer is consistent with the correct answer (if the AI assistant’s final answer is missing or incomplete, treat it as inconsistent). Provide your conclusion, consistent or inconsistent, in English within <result></result> tags, i.e., <result>consistent</result> or <result>inconsistent</result>

Do not output anything other than the above.
Output:
'''.strip()

IMPROVED_PROMPT_TEMPLATE = '''I will now give you a question, an answer generated by an AI assistant, and the correct answer to the question. Please compare the AI assistant's answer with the correct answer and determine whether they are consistent.

Important: You do not need to compute or solve the problem yourself. Just judge whether the AI Assistant Answer matches the provided Ground Truth; use the question text only as context if needed.

- ---------------- [Question Start] -----------------

{problem}

- ---------------- [Question End] -----------------
- ---------------- [AI Assistant Answer Start] -----------------

{pred}

- ---------------- [AI Assistant Answer End] -----------------
- ---------------- [Ground Truth Start] -----------------

{ground_truth}

- ---------------- [Ground Truth End] -----------------

Please structure your response in three lines:
1. Line 1: Analyze the AI assistant's answer
2. Line 2: Confirm what the correct answer is
3. Line 3: Analyze the question to judge whether the AI assistant's answer is consistent with the correct answer. Provide your conclusion, consistent or inconsistent, in English within <result></result> tags, i.e., <result>consistent</result> or <result>inconsistent</result>
Do not output anything other than the above.


Output:
'''.strip()


GENRM_PROMPT_TEMPLATE = '''I will now give you a question, an answer generated by an AI assistant, and the correct answer to the question. Please compare the AI assistant's answer with the correct answer and determine whether they are consistent.

- ---------------- [Question Start] -----------------

{problem}

- ---------------- [Question End] -----------------
- ---------------- [AI Assistant Answer Start] -----------------

{pred}

- ---------------- [AI Assistant Answer End] -----------------
- ---------------- [Ground Truth Start] -----------------

{ground_truth}

- ---------------- [Ground Truth End] -----------------

Please structure your response in three lines:
1. Line 1: Analyze the AI assistant's answer
2. Line 2: Confirm what the correct answer is
3. Line 3: Analyze the question to judge whether the AI assistant's answer is consistent with the correct answer. Provide your conclusion, consistent or inconsistent, in English within <result></result> tags, i.e., <result>consistent</result> or <result>inconsistent</result>
Do not output anything other than the above.


Output:
'''.strip()



def save_to_jsonl(prompt, response):
    record = {
        "prompt": prompt,
        "response": response
    }
    print(record)
    with open(SAVE_JUDGE_PATH, 'a', encoding='utf-8') as f:
        f.write(json.dumps(record, ensure_ascii=False) + '\n')

def match_answer_content(processed_str, answer_pattern = r"(?i)Answer\s*:\s*([^\n]+)"):
    matches = list(re.finditer(answer_pattern, processed_str, re.DOTALL))
    if not matches:
        # print("verify <answer> not matches, return None")
        # print("[Error] No valid answer tags found")
        return None
    final_answer = matches[-1].group(1).strip()
    # print("verify <answer> matches, return final_answer")
    # print(final_answer)
    return final_answer


def get_response_by_generate(problem, pred, ground_truth):
    prompt = IMPROVED_PROMPT_TEMPLATE.format(problem=problem, pred=pred, ground_truth=ground_truth)
    messages = [{"role": "user", "content": prompt}]


    gen_args = {
        "model_name": MODEL_NAME,
        "temperature": 0.0,
        "top_p": 1.0,
        "max_tokens": 500,
        "workers": 32
        # "chat_template_kwargs": {"enable_thinking": False} # nothinking for qwen3 by hwq 0702
    }


    try:
        client = OpenAIClientTool(
            name=MODEL_NAME,
            api_key=API_KEY,
            base_url=BASE_URL
        )
        judge_raw_output = client.generate(messages, **gen_args)
        response = judge_raw_output[0]
        # response = completions.choices[0].message.content
        # save_to_jsonl(prompt, response)
        return response
    except Exception as e:
        print(f"Exception: {e}")
        return None


def get_response_by_batch_generate(problems, preds, ground_truths):
    # prompt = GENRM_PROMPT_TEMPLATE.format(problem=problem, pred=pred, ground_truth=ground_truth)
    # messages = [{"role": "user", "content": prompt}]
    batch_messages = []
    prompts = []

    for idx, (problem, pred, ground_truth) in enumerate(zip(problems, preds, ground_truths)):
        # print("problem")
        # print(problem[0].get("content"))
        prompt = IMPROVED_PROMPT_TEMPLATE.format(
            problem=problem[0].get("content"),
            pred=pred,
            ground_truth=ground_truth
        )
        prompts.append(prompt)
        batch_messages.append({
            "id": idx,
            "messages": [{"role": "user", "content": prompt}],
            "response_index": 0  # 只取 top-1
        })

    gen_args = {
        "model_name": MODEL_NAME,
        "temperature": 0.0,
        "top_p": 1.0,
        "max_tokens": 500,
        "workers": 32
        # "chat_template_kwargs": {"enable_thinking": False} # nothinking for qwen3 by hwq 0702
    }
    try:
        client = OpenAIClientTool(
            name=MODEL_NAME,
            api_key=API_KEY,
            base_url=BASE_URL
        )
        # judge_raw_output = client.generate(messages, **gen_args)
        # response = judge_raw_output[0]
        # # response = completions.choices[0].message.content
        # save_to_jsonl(prompt, response)
        # return response
        # 批量调用
        resp_map = client.batch_generate(batch_messages, **gen_args)

        # 还原顺序并提取 response[0]
        responses = []
        for i in range(len(prompts)):
            entry = resp_map.get(i)
            if entry and entry["responses"]:
                resp = entry["responses"][0]
            else:
                resp = None
            responses.append(resp)
            save_to_jsonl(prompts[i], resp)

        return responses
    # except Exception as e:
    #     print(f"Exception: {e}")
    #     return None
    except Exception as e:
        print(f"[BatchGenerate Exception]: {e}")
        return [None] * len(prompts)

def get_response_by_batch_generate_from_response(problems, preds, ground_truths):
    # prompt = GENRM_PROMPT_TEMPLATE.format(problem=problem, pred=pred, ground_truth=ground_truth)
    # messages = [{"role": "user", "content": prompt}]
    batch_messages = []
    prompts = []

    for idx, (problem, pred, ground_truth) in enumerate(zip(problems, preds, ground_truths)):
        # print("problem")
        # print(problem[0].get("content"))
        prompt = PROMPT_TEMPLATE_FROM_RESPONSE.format(
            problem=problem[0].get("content"),
            pred=pred,
            ground_truth=ground_truth
        )
        prompts.append(prompt)
        batch_messages.append({
            "id": idx,
            "messages": [{"role": "user", "content": prompt}],
            "response_index": 0  # 只取 top-1
        })

    gen_args = {
        "model_name": MODEL_NAME,
        "temperature": 0.0,
        "top_p": 1.0,
        "max_tokens": 500,
        "workers": 32
        # "chat_template_kwargs": {"enable_thinking": False} # nothinking for qwen3 by hwq 0702
    }
    try:
        client = OpenAIClientTool(
            name=MODEL_NAME,
            api_key=API_KEY,
            base_url=BASE_URL
        )
        # judge_raw_output = client.generate(messages, **gen_args)
        # response = judge_raw_output[0]
        # # response = completions.choices[0].message.content
        # save_to_jsonl(prompt, response)
        # return response
        # 批量调用
        resp_map = client.batch_generate(batch_messages, **gen_args)

        # 还原顺序并提取 response[0]
        responses = []
        for i in range(len(prompts)):
            entry = resp_map.get(i)
            if entry and entry["responses"]:
                resp = entry["responses"][0]
            else:
                resp = None
            responses.append(resp)
            save_to_jsonl(prompts[i], resp)

        return responses
    # except Exception as e:
    #     print(f"Exception: {e}")
    #     return None
    except Exception as e:
        print(f"[BatchGenerate Exception]: {e}")
        return [None] * len(prompts)


def compute_reward(response):
    reward_score = 0.0
    try:
        boxed_result = last_boxed_only_string(response)
        if boxed_result is not None:
            result = remove_boxed(boxed_result)
            reward_score = float(result == "True")
    except Exception as e:
        print(e)
    return reward_score

def compute_reward_result_tag(judge_response):
    reward_score = 0.0
    acc = 0
    result_match = re.findall(r"<result>(.*?)</result>", judge_response)
    if result_match and len(result_match) >= 1:
        try:
            judge_item_res = True if result_match[-1].strip().lower() == "consistent" else False
            acc = 1 if judge_item_res else -1
        except Exception as e:
            print("match error")
            acc = 0
    return acc


def compute_score(data_source, solution_str, ground_truth, extra_info):

    # problem = extra_info["question"]
    problem = extra_info
    response_str = solution_str[-300:]  # The longest answer in MATH-500 has 159 characters
    # 按照 pattern 抽取出答案的部分
    pred = match_answer_content(
        response_str,
        # dapo prompt
        answer_pattern=r"(?i)Answer\s*:\s*([^\n]+)"
        # answer_pattern = r"\\boxed\s*{([^}]*)}"
    )
    # 根据 box 里面的内容判断（如果有 boxed 的话）
    format_correct = -1.0
    answer_correct = -1.0
    if pred is not None:
        format_correct = 1.0
    response = get_response_by_generate(problem, pred, ground_truth)
    if response is not None:
        answer_correct = compute_reward_result_tag(response)
    else:
        answer_correct = 0.0

    if format_correct < 0:
        reward = format_correct
    else:
        reward = answer_correct

    correct = 0 if reward <= 0 else reward
    acc = correct
    # 和dapo奖励一致 格式错-1，格式对答案错-1，格式对答案对1
    return {
        "score": reward,
        "acc": answer_correct,
        "pred": "" if pred is None else pred,
        # "answer_correct": answer_correct,
    }

def compute_score_batched(data_sources, solution_strs, ground_truths, extra_infos):
    # from remote_reward.tools.match import match_answer_content  # 确保正确引入
    # from remote_reward import get_response_by_generate, compute_reward_result_tag
    problems = extra_infos
    # 提前截断 response，并抽取 pred
    response_strs = [s[-300:] for s in solution_strs]
    preds = [
        match_answer_content(resp, answer_pattern=r"(?i)Answer\s*:\s*([^\n]+)")
        for resp in response_strs
    ]


    # 用 get_response_by_generate 并发地去询问 judge model（利用 batched_generate_single 包装的）
    responses = get_response_by_batch_generate(problems, preds, ground_truths)

    results = []
    for pred, resp in zip(preds, responses):
        if pred is not None:
            format_correct = 1.0
        else:
            format_correct = -1.0

        if resp is not None:
            answer_correct = compute_reward_result_tag(resp)
        else:
            answer_correct = 0.0

        if format_correct < 0:
            reward = format_correct
        else:
            reward = answer_correct
        acc = 1.0 if answer_correct == 1.0 else 0.0

        result = {
            "score": reward,
            "acc": acc,
            "pred": "" if pred is None else pred
        }
        results.append(result)

    return results


def compute_score_batched_from_response(data_sources, solution_strs, ground_truths, extra_infos):
    # from remote_reward.tools.match import match_answer_content  # 确保正确引入
    # from remote_reward import get_response_by_generate, compute_reward_result_tag
    problems = extra_infos
    # 提前截断 response，并抽取 pred
    response_strs = [s[-300:] for s in solution_strs]
    preds = response_strs


    # 用 get_response_by_generate 并发地去询问 judge model（利用 batched_generate_single 包装的）
    responses = get_response_by_batch_generate_from_response(problems, preds, ground_truths)

    results = []
    for pred, resp in zip(preds, responses):
        if pred is not None:
            format_correct = 1.0
        else:
            format_correct = -1.0

        if resp is not None:
            answer_correct = compute_reward_result_tag(resp)
        else:
            answer_correct = 0.0

        if format_correct < 0:
            reward = format_correct
        else:
            reward = answer_correct
        acc = 1.0 if answer_correct == 1.0 else 0.0

        result = {
            "score": reward,
            "acc": acc,
            "pred": "" if pred is None else pred
        }
        results.append(result)

    return results
